-- =============================================================================
-- COMBINED MIGRATION FILE — 0001 through 0019
-- =============================================================================
-- Auto-generated by concatenating supabase/migrations/0001_*.sql through
-- 0019_*.sql, in order, unmodified. This file exists purely as a
-- convenience for pasting into the Supabase SQL Editor in one go instead
-- of running 19 files one at a time.
--
-- IMPORTANT:
--   - The individual numbered files in supabase/migrations/ remain the
--     source of truth for the project's migration history. Do not edit
--     this combined file and expect it to stay in sync — regenerate it
--     from the individual files if anything changes.
--   - Every statement in every file below uses "if not exists" /
--     "create or replace" / "on conflict do nothing", so this whole file
--     is safe to run more than once against the same database.
--   - Run this against the SAME Supabase project already configured for
--     this app (VITE_SUPABASE_URL). Do not run it against a different
--     project.
--   - This file only creates schema/functions/seed reference data (plans).
--     It does NOT include supabase/seed/0001_dev_seed.sql (dev-only test
--     accounts), which is intentionally kept separate — see that file's
--     own header for why.
-- =============================================================================


-- #############################################################################
-- FILE: supabase/migrations/0001_extensions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0001_extensions.sql
-- Purpose  : Enable Postgres extensions required by the SaaS platform.
-- =============================================================================

-- UUID generation (gen_random_uuid is also available natively via pgcrypto)
create extension if not exists "pgcrypto";

-- Useful for case-insensitive text comparisons later (e.g. emails)
create extension if not exists "citext";


-- #############################################################################
-- FILE: supabase/migrations/0002_helper_functions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0002_helper_functions.sql
-- Purpose  : Reusable helper functions/triggers shared across every table.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- set_updated_at()
-- Generic trigger function that stamps NEW.updated_at with the current time
-- on every UPDATE. Attached per-table in each table's migration file so that
-- no application code is ever responsible for maintaining updated_at.
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Trigger function: sets NEW.updated_at = now() on every row update. Attach via
   "create trigger trg_<table>_updated_at before update on <table> for each row
   execute function public.set_updated_at();"';


-- #############################################################################
-- FILE: supabase/migrations/0003_saas_admins.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0003_saas_admins.sql
-- Purpose  : Platform-level administrators who control the entire SaaS system.
--            These are NOT store users. Authentication is custom (see docs).
-- =============================================================================

create table if not exists public.saas_admins (
  id                  uuid primary key default gen_random_uuid(),

  login_id            citext not null,
  password_hash       text not null,

  full_name           text not null,
  phone               text,

  status              text not null default 'active'
                       check (status in ('active', 'disabled')),

  last_login_at       timestamptz,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint saas_admins_login_id_key unique (login_id)
);

comment on table public.saas_admins is
  'Platform-level administrators. Distinct from store_users. Custom auth only — no Supabase Auth.';
comment on column public.saas_admins.password_hash is
  'Argon2id/bcrypt hash produced by a trusted server-side function. Never store or compare plain text.';

create index if not exists idx_saas_admins_status on public.saas_admins (status);

create trigger trg_saas_admins_updated_at
  before update on public.saas_admins
  for each row
  execute function public.set_updated_at();

-- Row Level Security: the anon/public key must never be able to read or write
-- this table directly. All access happens through trusted server-side
-- functions using the service role, which bypasses RLS by design. Enabling
-- RLS here with no permissive policies means the anon/authenticated roles are
-- hard-blocked at the database layer as defense-in-depth.
alter table public.saas_admins enable row level security;
-- Intentionally no policies are created: default-deny for anon/authenticated.


-- #############################################################################
-- FILE: supabase/migrations/0004_store_code_sequence.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0004_store_code_sequence.sql
-- Purpose  : Concurrency-safe generation of human-readable Store IDs
--            (e.g. STORE-0001, STORE-0002, ...) using a real Postgres SEQUENCE.
--            A sequence guarantees no two concurrent store-creation requests
--            can ever receive the same number, without needing application-side
--            locking or "select max()+1" races.
-- =============================================================================

create sequence if not exists public.store_code_seq
  as bigint
  start with 1
  increment by 1
  no cycle;

-- -----------------------------------------------------------------------------
-- generate_store_code()
-- Returns the next formatted store code, e.g. 'STORE-0001'.
-- Padding is 4 digits by default; once the sequence exceeds 9999 the code
-- simply grows to 'STORE-10000', etc. Centralizing the format here means the
-- prefix/padding can be changed later in one place without touching app code.
-- -----------------------------------------------------------------------------
create or replace function public.generate_store_code()
returns text
language plpgsql
as $$
declare
  next_val bigint;
begin
  next_val := nextval('public.store_code_seq');
  return 'STORE-' || lpad(next_val::text, 4, '0');
end;
$$;

comment on function public.generate_store_code() is
  'Concurrency-safe next human-readable store code, e.g. STORE-0001. Backed by a
   real sequence so simultaneous store creations never collide. Call this only
   from trusted server-side store-creation logic, never from the browser.';


-- #############################################################################
-- FILE: supabase/migrations/0005_stores.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0005_stores.sql
-- Purpose  : The tenant table. Every store is one clothing-store business
--            using the SaaS platform. All future business tables hang off
--            store_id (see 0999_tenant_convention_notes.sql).
-- =============================================================================

create table if not exists public.stores (
  id                  uuid primary key default gen_random_uuid(),

  -- Human-readable identifier, e.g. STORE-0001. Generated server-side via
  -- generate_store_code(); never used as a primary/foreign key.
  store_code          text not null default public.generate_store_code(),

  business_name       text not null,
  legal_name          text,

  owner_name          text not null,
  mobile              text not null,
  whatsapp            text,
  email                citext,

  address_line_1      text not null,
  address_line_2      text,
  city                text,
  state               text,
  country             text not null,
  postal_code         text,

  currency_code       text not null default 'QAR',
  timezone            text not null default 'Asia/Qatar',
  tax_number          text,

  logo_url            text,

  -- Soft-deletion lifecycle. Stores are archived, never hard-deleted, so that
  -- historical business records (invoices, audit logs, etc.) remain valid.
  status              text not null default 'active'
                       check (status in ('active', 'suspended', 'inactive', 'archived')),

  created_by          uuid references public.saas_admins (id) on delete set null,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint stores_store_code_key unique (store_code),
  constraint stores_currency_code_len check (char_length(currency_code) = 3)
);

comment on table public.stores is
  'Tenant table. One row per clothing-store business on the SaaS platform.';
comment on column public.stores.store_code is
  'Human-readable ID (STORE-0001). Display/reference only — never a FK target.';
comment on column public.stores.status is
  'active | suspended | inactive | archived. Stores are archived, never hard-deleted.';

create index if not exists idx_stores_store_code on public.stores (store_code);
create index if not exists idx_stores_status on public.stores (status);

create trigger trg_stores_updated_at
  before update on public.stores
  for each row
  execute function public.set_updated_at();

alter table public.stores enable row level security;
-- No anon/authenticated policies: all reads/writes go through trusted
-- server-side endpoints that use the service role and enforce tenant
-- authorization from a validated session (see docs/ARCHITECTURE.md).


-- #############################################################################
-- FILE: supabase/migrations/0006_roles_permissions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0006_roles_permissions.sql
-- Purpose  : Role-based access control foundation.
--            - roles: either a system role (store_id is null) reusable across
--              all stores as a template, or a store-specific role.
--            - permissions: the fixed catalogue of fine-grained capabilities.
--            - role_permissions: join table assigning permissions to roles.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- roles
-- -----------------------------------------------------------------------------
create table if not exists public.roles (
  id                  uuid primary key default gen_random_uuid(),

  -- NULL store_id => system/template role (e.g. a default "Store Admin"
  -- template maintained by the SaaS platform). Non-null => a role that
  -- belongs to, and is only usable within, that specific store.
  store_id            uuid references public.stores (id) on delete cascade,

  name                text not null,
  description         text,

  is_system_role      boolean not null default false,

  status              text not null default 'active'
                       check (status in ('active', 'disabled')),

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- A role name must be unique within its scope (per store, or among the
  -- global system roles when store_id is null).
  constraint roles_store_name_key unique (store_id, name)
);

comment on table public.roles is
  'RBAC roles. store_id NULL = platform/system template role. store_id set = store-owned role.';

create index if not exists idx_roles_store_id on public.roles (store_id);
create index if not exists idx_roles_status on public.roles (status);

create trigger trg_roles_updated_at
  before update on public.roles
  for each row
  execute function public.set_updated_at();

alter table public.roles enable row level security;

-- -----------------------------------------------------------------------------
-- permissions
-- -----------------------------------------------------------------------------
create table if not exists public.permissions (
  id                  uuid primary key default gen_random_uuid(),

  -- e.g. 'sales.create'
  permission_key      text not null,
  module              text not null,
  action               text not null,
  description         text,

  created_at          timestamptz not null default now(),

  constraint permissions_permission_key_key unique (permission_key)
);

comment on table public.permissions is
  'Fixed catalogue of fine-grained permission keys, e.g. sales.create, inventory.adjust.';

create index if not exists idx_permissions_module on public.permissions (module);

alter table public.permissions enable row level security;

-- -----------------------------------------------------------------------------
-- role_permissions
-- -----------------------------------------------------------------------------
create table if not exists public.role_permissions (
  id                  uuid primary key default gen_random_uuid(),

  role_id             uuid not null references public.roles (id) on delete cascade,
  permission_id       uuid not null references public.permissions (id) on delete cascade,

  created_at          timestamptz not null default now(),

  constraint role_permissions_role_permission_key unique (role_id, permission_id)
);

comment on table public.role_permissions is
  'Join table: which permissions are granted to which role.';

create index if not exists idx_role_permissions_role_id on public.role_permissions (role_id);
create index if not exists idx_role_permissions_permission_id on public.role_permissions (permission_id);

alter table public.role_permissions enable row level security;


-- #############################################################################
-- FILE: supabase/migrations/0007_store_users.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0007_store_users.sql
-- Purpose  : Users that belong to a specific store (cashiers, managers, etc).
--            Custom auth: login_id + password_hash, scoped uniquely per store.
-- =============================================================================

create table if not exists public.store_users (
  id                     uuid primary key default gen_random_uuid(),

  store_id               uuid not null references public.stores (id) on delete cascade,

  login_id               citext not null,
  password_hash          text not null,

  full_name              text not null,
  phone                  text,

  -- Prefer disabling a role over deleting it while users depend on it
  -- (enforced procedurally in Phase 2/3 application logic; see roles table).
  role_id                uuid references public.roles (id) on delete set null,

  status                 text not null default 'active'
                          check (status in ('active', 'disabled', 'locked')),

  -- Brute-force protection fields, used by the Phase 2 login endpoint.
  failed_login_attempts  integer not null default 0,
  locked_until           timestamptz,

  password_changed_at    timestamptz not null default now(),
  last_login_at          timestamptz,

  created_by             uuid references public.store_users (id) on delete set null,

  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  -- Username only needs to be unique WITHIN a store, so STORE-0001/admin and
  -- STORE-0002/admin can coexist, but STORE-0001/admin cannot be duplicated.
  constraint store_users_store_login_key unique (store_id, login_id)
);

comment on table public.store_users is
  'Users belonging to a single store. login_id is unique per store_id, not globally.';
comment on column public.store_users.password_hash is
  'Argon2id/bcrypt hash produced by a trusted server-side function. Never store or compare plain text.';

create index if not exists idx_store_users_store_id on public.store_users (store_id);
create index if not exists idx_store_users_store_login on public.store_users (store_id, login_id);
create index if not exists idx_store_users_status on public.store_users (status);
create index if not exists idx_store_users_role_id on public.store_users (role_id);

create trigger trg_store_users_updated_at
  before update on public.store_users
  for each row
  execute function public.set_updated_at();

alter table public.store_users enable row level security;
-- No anon/authenticated policies: reads/writes only via trusted server-side
-- endpoints. The application layer is responsible for scoping every query by
-- the store_id resolved from a verified session (never from client input).


-- #############################################################################
-- FILE: supabase/migrations/0008_sessions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0008_sessions.sql
-- Purpose  : Server-managed session storage for the custom auth system.
--
-- DESIGN DECISION (documented per Phase-1 spec §15):
-- We use TWO separate, strongly-typed session tables instead of one
-- polymorphic "user_sessions" table with a nullable user_id/admin_id pair.
--
-- Why:
--   - A single polymorphic table (user_id + session_type discriminator, no
--     real FK) cannot enforce referential integrity at the database level —
--     a bad session_type or mismatched id would silently point nowhere.
--   - saas_admins and store_users are different entities with different
--     lifecycles, blast radii, and security sensitivity (a platform-admin
--     session compromise is far more severe than a single store's cashier
--     session). Keeping them in separate tables makes it impossible for a
--     bug to accidentally treat one kind of session as the other.
--   - Real foreign keys + real CASCADE behavior are available on both
--     tables, which is not possible with a single polymorphic user_id column.
--
-- A thin view (public.v_all_sessions) is provided below for the rare cases
-- (admin dashboards, audit tooling) that want a unified read-only look
-- across both tables.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- store_user_sessions
-- -----------------------------------------------------------------------------
create table if not exists public.store_user_sessions (
  id                  uuid primary key default gen_random_uuid(),

  store_user_id       uuid not null references public.store_users (id) on delete cascade,
  store_id            uuid not null references public.stores (id) on delete cascade,

  -- Only a SHA-256 (or similar) hash of the opaque session token is stored.
  -- The raw token is returned to the client exactly once at login time and
  -- never persisted server-side.
  token_hash          text not null,

  created_at          timestamptz not null default now(),
  expires_at          timestamptz not null,
  last_activity_at    timestamptz not null default now(),
  revoked_at          timestamptz,

  ip_address          text,
  user_agent          text,
  device_name         text,

  constraint store_user_sessions_token_hash_key unique (token_hash)
);

comment on table public.store_user_sessions is
  'Server-side sessions for store_users. Only a hash of the session token is stored.';

create index if not exists idx_store_user_sessions_user_id on public.store_user_sessions (store_user_id);
create index if not exists idx_store_user_sessions_store_id on public.store_user_sessions (store_id);
create index if not exists idx_store_user_sessions_token_hash on public.store_user_sessions (token_hash);
create index if not exists idx_store_user_sessions_expires_at on public.store_user_sessions (expires_at);

alter table public.store_user_sessions enable row level security;

-- -----------------------------------------------------------------------------
-- saas_admin_sessions
-- -----------------------------------------------------------------------------
create table if not exists public.saas_admin_sessions (
  id                  uuid primary key default gen_random_uuid(),

  saas_admin_id       uuid not null references public.saas_admins (id) on delete cascade,

  token_hash          text not null,

  created_at          timestamptz not null default now(),
  expires_at          timestamptz not null,
  last_activity_at    timestamptz not null default now(),
  revoked_at          timestamptz,

  ip_address          text,
  user_agent          text,
  device_name         text,

  constraint saas_admin_sessions_token_hash_key unique (token_hash)
);

comment on table public.saas_admin_sessions is
  'Server-side sessions for saas_admins. Only a hash of the session token is stored.';

create index if not exists idx_saas_admin_sessions_admin_id on public.saas_admin_sessions (saas_admin_id);
create index if not exists idx_saas_admin_sessions_token_hash on public.saas_admin_sessions (token_hash);
create index if not exists idx_saas_admin_sessions_expires_at on public.saas_admin_sessions (expires_at);

alter table public.saas_admin_sessions enable row level security;

-- -----------------------------------------------------------------------------
-- Unified read-only view (optional convenience for cross-cutting tooling).
-- session_type mirrors the "session_type" concept requested in the spec
-- while keeping the underlying storage strongly typed and normalized.
-- -----------------------------------------------------------------------------
create or replace view public.v_all_sessions as
select
  id,
  'store_user'::text as session_type,
  store_user_id as principal_id,
  store_id,
  token_hash,
  created_at,
  expires_at,
  last_activity_at,
  revoked_at,
  ip_address,
  user_agent,
  device_name
from public.store_user_sessions
union all
select
  id,
  'saas_admin'::text as session_type,
  saas_admin_id as principal_id,
  null::uuid as store_id,
  token_hash,
  created_at,
  expires_at,
  last_activity_at,
  revoked_at,
  ip_address,
  user_agent,
  device_name
from public.saas_admin_sessions;

comment on view public.v_all_sessions is
  'Read-only union of store_user_sessions and saas_admin_sessions for cross-cutting tooling/audits.';


-- #############################################################################
-- FILE: supabase/migrations/0009_settings.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0009_settings.sql
-- Purpose  : Key/value settings storage, clearly separated by scope so tenant
--            boundaries stay unambiguous. Store-level and platform-level
--            settings are never mixed in the same table.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- store_settings — per-store configuration (invoice format, receipt config,
-- tax preferences, loyalty settings, POS settings, etc. added in later phases)
-- -----------------------------------------------------------------------------
create table if not exists public.store_settings (
  id                  uuid primary key default gen_random_uuid(),

  store_id            uuid not null references public.stores (id) on delete cascade,

  setting_key         text not null,
  setting_value       jsonb not null default '{}'::jsonb,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint store_settings_store_key_key unique (store_id, setting_key)
);

comment on table public.store_settings is
  'Per-store key/value settings (JSONB). High-frequency critical settings may
   graduate to dedicated columns/tables in later phases.';

create index if not exists idx_store_settings_store_id on public.store_settings (store_id);

create trigger trg_store_settings_updated_at
  before update on public.store_settings
  for each row
  execute function public.set_updated_at();

alter table public.store_settings enable row level security;

-- -----------------------------------------------------------------------------
-- saas_settings — platform-level configuration only, never store data.
-- -----------------------------------------------------------------------------
create table if not exists public.saas_settings (
  id                  uuid primary key default gen_random_uuid(),

  setting_key         text not null,
  setting_value       jsonb not null default '{}'::jsonb,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint saas_settings_setting_key_key unique (setting_key)
);

comment on table public.saas_settings is
  'Platform-wide key/value settings (JSONB). Never store tenant-specific data here.';

create trigger trg_saas_settings_updated_at
  before update on public.saas_settings
  for each row
  execute function public.set_updated_at();

alter table public.saas_settings enable row level security;


-- #############################################################################
-- FILE: supabase/migrations/0010_audit_logs.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0010_audit_logs.sql
-- Purpose  : Durable, server-persisted audit trail. Never rely on frontend
--            state for audit history — every important action must be written
--            here by trusted server-side logic.
-- =============================================================================

create table if not exists public.audit_logs (
  id                  uuid primary key default gen_random_uuid(),

  -- Nullable because platform-level events (e.g. a SaaS admin creating a
  -- store) are not scoped to any single store.
  store_id            uuid references public.stores (id) on delete set null,

  -- Exactly one of saas_admin_id / store_user_id is expected to be set for
  -- actor-attributed events; both may be null for system-generated events.
  saas_admin_id       uuid references public.saas_admins (id) on delete set null,
  store_user_id       uuid references public.store_users (id) on delete set null,

  module              text not null,
  action              text not null,

  entity_type         text,
  entity_id           uuid,

  old_values          jsonb,
  new_values          jsonb,
  metadata            jsonb,

  ip_address          text,

  created_at          timestamptz not null default now()
);

comment on table public.audit_logs is
  'Append-only audit trail. Written exclusively by trusted server-side logic.
   Examples of action values: login_success, login_failed, store_created,
   user_created, password_reset, role_changed, product_price_changed,
   stock_adjusted, invoice_cancelled.';

create index if not exists idx_audit_logs_store_created on public.audit_logs (store_id, created_at);
create index if not exists idx_audit_logs_module_action on public.audit_logs (module, action);
create index if not exists idx_audit_logs_entity on public.audit_logs (entity_type, entity_id);

alter table public.audit_logs enable row level security;
-- No anon/authenticated policies: audit_logs is written and read exclusively
-- through trusted server-side endpoints (service role), never directly from
-- the browser.


-- #############################################################################
-- FILE: supabase/migrations/0011_login_rate_limits.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0011_login_rate_limits.sql
-- Purpose  : Backend login rate limiting. Edge Functions are stateless
--            between invocations, so in-memory rate limiting doesn't work —
--            counts are tracked here instead, keyed by a coarse "scope" and
--            a time-bucketed window.
--
-- Design: a fixed-window counter per (scope, scope_key, window_start).
-- scope is one of 'ip', 'store_login' (store_id+login_id combined), or
-- 'saas_login' (saas admin login_id). This lets the login endpoint check
-- multiple independent limits (e.g. "this IP" AND "this specific account")
-- without one bad actor being able to lock out a legitimate user sharing
-- their IP, and without only relying on a per-account counter that a
-- distributed attacker could dodge by spreading attempts across accounts.
-- =============================================================================

create table if not exists public.login_rate_limits (
  id                  uuid primary key default gen_random_uuid(),

  scope               text not null check (scope in ('ip', 'store_login', 'saas_login')),
  scope_key           text not null,

  -- Fixed-window bucket start (e.g. truncated to the minute). The login
  -- endpoint computes this the same way on read and write.
  window_start        timestamptz not null,

  attempt_count        integer not null default 1,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint login_rate_limits_scope_key_window_key unique (scope, scope_key, window_start)
);

comment on table public.login_rate_limits is
  'Fixed-window login attempt counters for rate limiting, keyed by scope
   (ip | store_login | saas_login). Written only by trusted server-side
   login endpoints. Old rows can be pruned periodically (e.g. > 1 day old).';

create index if not exists idx_login_rate_limits_scope_key on public.login_rate_limits (scope, scope_key, window_start);

create trigger trg_login_rate_limits_updated_at
  before update on public.login_rate_limits
  for each row
  execute function public.set_updated_at();

alter table public.login_rate_limits enable row level security;
-- No anon/authenticated policies: written/read exclusively by trusted
-- server-side login logic using the service role.


-- #############################################################################
-- FILE: supabase/migrations/0012_saas_admin_lockout_fields.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0012_saas_admin_lockout_fields.sql
-- Purpose  : Phase 1's saas_admins table didn't include failed-login lockout
--            tracking (only store_users did). Phase 2 needs the same
--            brute-force protection for SaaS admin accounts, so this adds
--            the matching columns. Forward migration — no data loss, all
--            new columns are nullable/defaulted.
-- =============================================================================

alter table public.saas_admins
  add column if not exists failed_login_attempts integer not null default 0,
  add column if not exists locked_until timestamptz;

comment on column public.saas_admins.failed_login_attempts is
  'Consecutive failed login attempts since the last success. Reset to 0 on successful login.';
comment on column public.saas_admins.locked_until is
  'If set and in the future, login is blocked until this time regardless of password correctness.';


-- #############################################################################
-- FILE: supabase/migrations/0013_auth_helper_functions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0013_auth_helper_functions.sql
-- Purpose  : Atomic, race-condition-safe helper functions used by the Phase 2
--            login endpoints. Doing these as single SQL statements (upsert /
--            update ... returning) avoids read-then-write races that plain
--            "select count, then update" application code would have under
--            concurrent login attempts (e.g. two parallel brute-force
--            requests both reading failed_login_attempts=4 and only one
--            increment landing).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- increment_login_rate_limit
-- Atomically increments (or creates) the counter for a given scope/key/window
-- and returns the resulting count. Callers compare the returned count against
-- their configured threshold.
-- -----------------------------------------------------------------------------
create or replace function public.increment_login_rate_limit(
  p_scope text,
  p_scope_key text,
  p_window_start timestamptz
)
returns integer
language sql
as $$
  insert into public.login_rate_limits (scope, scope_key, window_start, attempt_count)
  values (p_scope, p_scope_key, p_window_start, 1)
  on conflict (scope, scope_key, window_start)
  do update set attempt_count = public.login_rate_limits.attempt_count + 1
  returning attempt_count;
$$;

comment on function public.increment_login_rate_limit(text, text, timestamptz) is
  'Atomically increments the login attempt counter for (scope, scope_key,
   window_start), creating the row if needed. Returns the new count.';

-- -----------------------------------------------------------------------------
-- register_store_user_failed_login
-- Atomically increments failed_login_attempts for a store_user and, if the
-- new count reaches p_lock_threshold, sets locked_until p_lock_minutes from
-- now. Returns the resulting (attempts, locked_until) as a row.
-- -----------------------------------------------------------------------------
create or replace function public.register_store_user_failed_login(
  p_store_user_id uuid,
  p_lock_threshold integer default 5,
  p_lock_minutes integer default 15
)
returns table (failed_login_attempts integer, locked_until timestamptz)
language sql
as $$
  update public.store_users
  set
    failed_login_attempts = public.store_users.failed_login_attempts + 1,
    locked_until = case
      when public.store_users.failed_login_attempts + 1 >= p_lock_threshold
        then now() + make_interval(mins => p_lock_minutes)
      else public.store_users.locked_until
    end
  where id = p_store_user_id
  returning public.store_users.failed_login_attempts, public.store_users.locked_until;
$$;

comment on function public.register_store_user_failed_login(uuid, integer, integer) is
  'Atomically increments a store_user''s failed_login_attempts and applies a
   temporary lock once the threshold is reached. Default: lock for 15 minutes
   after 5 consecutive failures.';

-- -----------------------------------------------------------------------------
-- reset_store_user_login_state
-- Called after a successful login: clears failure counters/lock and stamps
-- last_login_at.
-- -----------------------------------------------------------------------------
create or replace function public.reset_store_user_login_state(p_store_user_id uuid)
returns void
language sql
as $$
  update public.store_users
  set failed_login_attempts = 0,
      locked_until = null,
      last_login_at = now()
  where id = p_store_user_id;
$$;

comment on function public.reset_store_user_login_state(uuid) is
  'Clears failed_login_attempts/locked_until and stamps last_login_at after a successful store_user login.';

-- -----------------------------------------------------------------------------
-- Same pair for saas_admins.
-- -----------------------------------------------------------------------------
create or replace function public.register_saas_admin_failed_login(
  p_saas_admin_id uuid,
  p_lock_threshold integer default 5,
  p_lock_minutes integer default 15
)
returns table (failed_login_attempts integer, locked_until timestamptz)
language sql
as $$
  update public.saas_admins
  set
    failed_login_attempts = public.saas_admins.failed_login_attempts + 1,
    locked_until = case
      when public.saas_admins.failed_login_attempts + 1 >= p_lock_threshold
        then now() + make_interval(mins => p_lock_minutes)
      else public.saas_admins.locked_until
    end
  where id = p_saas_admin_id
  returning public.saas_admins.failed_login_attempts, public.saas_admins.locked_until;
$$;

comment on function public.register_saas_admin_failed_login(uuid, integer, integer) is
  'Atomically increments a saas_admin''s failed_login_attempts and applies a
   temporary lock once the threshold is reached.';

create or replace function public.reset_saas_admin_login_state(p_saas_admin_id uuid)
returns void
language sql
as $$
  update public.saas_admins
  set failed_login_attempts = 0,
      locked_until = null,
      last_login_at = now()
  where id = p_saas_admin_id;
$$;

comment on function public.reset_saas_admin_login_state(uuid) is
  'Clears failed_login_attempts/locked_until and stamps last_login_at after a successful saas_admin login.';


-- #############################################################################
-- FILE: supabase/migrations/0014_store_management_functions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0014_store_management_functions.sql
-- Purpose  : Phase 3 — SaaS Super Admin Store Management. Atomic store
--            creation (store + role + permissions + admin user + settings +
--            audit, all-or-nothing), plus safe status-change and session
--            revocation helpers used by the store management Edge Functions.
-- =============================================================================

-- pg_trgm powers the fuzzy/substring search indexes used below for the
-- store search endpoint (business name / owner name).
create extension if not exists "pg_trgm";

-- -----------------------------------------------------------------------------
-- create_store_with_admin
--
-- Runs the entire "create a tenant" flow as ONE Postgres function call, which
-- Postgres executes inside an implicit transaction — if any step raises, the
-- whole thing rolls back automatically (no store without an admin, no admin
-- without a role, no partially-initialized store). This is the safe
-- transactional implementation requested in Phase 3 §12/§48.
--
-- Password hashing does NOT happen in Postgres — p_password_hash is already
-- a bcrypt hash computed in the Edge Function (see
-- supabase/functions/_shared/password.ts) before calling this. Postgres has
-- no vetted, maintained bcrypt/argon2 implementation available by default
-- (no pgcrypto crypt() blowfish support is enabled here), and re-implementing
-- password hashing in SQL would create a second hashing code path to keep in
-- sync with the Edge Function one — a needless risk. Hashing stays in
-- trusted server-side JS/TS; this function just persists the result.
-- -----------------------------------------------------------------------------
create or replace function public.create_store_with_admin(
  p_business_name text,
  p_legal_name text,
  p_owner_name text,
  p_mobile text,
  p_whatsapp text,
  p_email text,
  p_address_line_1 text,
  p_address_line_2 text,
  p_city text,
  p_state text,
  p_country text,
  p_postal_code text,
  p_currency_code text,
  p_timezone text,
  p_tax_number text,
  p_created_by uuid,          -- saas_admins.id of the creator
  p_admin_full_name text,
  p_admin_login_id text,
  p_admin_password_hash text,
  p_admin_phone text
)
returns table (
  store_id uuid,
  store_code text,
  admin_user_id uuid,
  role_id uuid
)
language plpgsql
as $$
declare
  v_store_id uuid;
  v_store_code text;
  v_role_id uuid;
  v_admin_user_id uuid;
  v_permission_ids uuid[];
begin
  -- 1. Insert store (store_code generated by generate_store_code() default).
  insert into public.stores (
    business_name, legal_name, owner_name, mobile, whatsapp, email,
    address_line_1, address_line_2, city, state, country, postal_code,
    currency_code, timezone, tax_number, status, created_by
  ) values (
    p_business_name, nullif(p_legal_name, ''), p_owner_name, p_mobile, nullif(p_whatsapp, ''), nullif(p_email, ''),
    p_address_line_1, nullif(p_address_line_2, ''), nullif(p_city, ''), nullif(p_state, ''), p_country, nullif(p_postal_code, ''),
    p_currency_code, p_timezone, nullif(p_tax_number, ''), 'active', p_created_by
  )
  returning id, stores.store_code into v_store_id, v_store_code;

  -- 2. Create the store's "Store Admin" role if it doesn't already exist
  --    (defensive — a fresh store never has one yet, but this keeps the
  --    function idempotent-safe rather than erroring on a retry).
  select id into v_role_id
  from public.roles
  where store_id = v_store_id and name = 'Store Admin';

  if v_role_id is null then
    insert into public.roles (store_id, name, description, is_system_role, status)
    values (v_store_id, 'Store Admin', 'Full access within this store', false, 'active')
    returning id into v_role_id;
  end if;

  -- 3. Assign the foundation permissions available at this stage to the new
  --    role (all currently-seeded permissions — Phase 5 expands this set).
  select array_agg(id) into v_permission_ids from public.permissions;

  if v_permission_ids is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_role_id, unnest(v_permission_ids)
    on conflict (role_id, permission_id) do nothing;
  end if;

  -- 4. Create the initial Store Admin user (password already hashed by caller).
  insert into public.store_users (
    store_id, login_id, password_hash, full_name, phone, role_id, status, created_by
  ) values (
    v_store_id, p_admin_login_id, p_admin_password_hash, p_admin_full_name, nullif(p_admin_phone, ''), v_role_id, 'active', null
  )
  returning id into v_admin_user_id;

  -- 5. Default store settings row(s) — empty JSONB placeholders future
  --    phases will populate (invoice config, receipt config, etc).
  insert into public.store_settings (store_id, setting_key, setting_value)
  values (v_store_id, 'general', '{}'::jsonb)
  on conflict (store_id, setting_key) do nothing;

  -- 6. Audit entry (the Edge Function also writes its own higher-level
  --    audit row with the acting SaaS admin's IP; this one captures the
  --    atomic DB-side fact that the transaction completed).
  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, new_values)
  values (
    v_store_id, p_created_by, 'saas_store_management', 'store_created', 'store', v_store_id,
    jsonb_build_object('storeCode', v_store_code, 'businessName', p_business_name)
  );

  return query select v_store_id, v_store_code, v_admin_user_id, v_role_id;
end;
$$;

comment on function public.create_store_with_admin is
  'Atomically creates a store, its Store Admin role + permissions, the
   initial Store Admin user, default settings, and an audit entry. Runs in
   Postgres''s implicit function-call transaction: any exception rolls back
   the entire operation. Password must already be hashed by the caller.';

-- -----------------------------------------------------------------------------
-- set_store_status
--
-- Safe, audited status transition + session revocation in one call. Used by
-- the suspend/activate/archive Edge Function endpoints instead of a bare
-- `update stores set status = ...`, so revocation can never be forgotten.
-- -----------------------------------------------------------------------------
create or replace function public.set_store_status(
  p_store_id uuid,
  p_new_status text,
  p_saas_admin_id uuid
)
returns table (revoked_session_count integer)
language plpgsql
as $$
declare
  v_old_status text;
  v_revoked_count integer := 0;
begin
  if p_new_status not in ('active', 'suspended', 'inactive', 'archived') then
    raise exception 'invalid store status: %', p_new_status;
  end if;

  select status into v_old_status from public.stores where id = p_store_id for update;
  if v_old_status is null then
    raise exception 'store not found: %', p_store_id;
  end if;

  update public.stores set status = p_new_status where id = p_store_id;

  -- Revoke every active session for this store whenever it leaves 'active'
  -- status, so an old cookie can never keep working after suspend/archive.
  if p_new_status <> 'active' then
    with revoked as (
      update public.store_user_sessions
      set revoked_at = now()
      where store_id = p_store_id and revoked_at is null
      returning id
    )
    select count(*) into v_revoked_count from revoked;
  end if;

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, old_values, new_values)
  values (
    p_store_id, p_saas_admin_id, 'saas_store_management',
    case p_new_status
      when 'suspended' then 'store_suspended'
      when 'active' then 'store_activated'
      when 'archived' then 'store_archived'
      else 'store_updated'
    end,
    'store', p_store_id,
    jsonb_build_object('status', v_old_status),
    jsonb_build_object('status', p_new_status)
  );

  if v_revoked_count > 0 then
    insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, metadata)
    values (p_store_id, p_saas_admin_id, 'saas_store_management', 'store_sessions_revoked', 'store', p_store_id,
      jsonb_build_object('revokedCount', v_revoked_count));
  end if;

  return query select v_revoked_count;
end;
$$;

comment on function public.set_store_status is
  'Atomically updates a store''s status, revokes all its active store_user
   sessions if leaving "active" status, and writes audit log entries.';

-- -----------------------------------------------------------------------------
-- Indexes to support Phase 3 search/filter/pagination without full scans.
-- -----------------------------------------------------------------------------
create index if not exists idx_stores_country on public.stores (country);
create index if not exists idx_stores_created_at on public.stores (created_at desc);
-- Case-insensitive search across the fields the store list supports search on.
create index if not exists idx_stores_business_name_trgm on public.stores using gin (business_name gin_trgm_ops);
create index if not exists idx_stores_owner_name_trgm on public.stores using gin (owner_name gin_trgm_ops);


-- #############################################################################
-- FILE: supabase/migrations/0015_store_list_and_dashboard.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0015_store_list_and_dashboard.sql
-- Purpose  : Server-side search/filter/pagination for the SaaS store list,
--            and aggregate counts for the SaaS dashboard — both as SQL
--            functions so the Edge Functions issue one round-trip instead of
--            fetching everything and filtering/counting in JS.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- list_stores
-- Server-side search + filter + pagination. Returns a page of stores plus
-- each store's user counts and a total row count (for computing total pages)
-- in a single query.
-- -----------------------------------------------------------------------------
create or replace function public.list_stores(
  p_search text default null,
  p_status text default null,
  p_country text default null,
  p_page integer default 1,
  p_page_size integer default 20
)
returns table (
  id uuid,
  store_code text,
  business_name text,
  owner_name text,
  mobile text,
  country text,
  currency_code text,
  status text,
  created_at timestamptz,
  user_count bigint,
  total_count bigint
)
language sql
stable
as $$
  with filtered as (
    select s.*
    from public.stores s
    where (p_status is null or s.status = p_status)
      and (p_country is null or s.country = p_country)
      and (
        p_search is null or p_search = '' or
        s.store_code ilike '%' || p_search || '%' or
        s.business_name ilike '%' || p_search || '%' or
        s.owner_name ilike '%' || p_search || '%' or
        s.mobile ilike '%' || p_search || '%' or
        s.email::text ilike '%' || p_search || '%'
      )
  ),
  counted as (
    select count(*) as total from filtered
  )
  select
    f.id, f.store_code, f.business_name, f.owner_name, f.mobile, f.country,
    f.currency_code, f.status, f.created_at,
    coalesce(u.user_count, 0) as user_count,
    counted.total as total_count
  from filtered f
  left join (
    select store_id, count(*) as user_count from public.store_users group by store_id
  ) u on u.store_id = f.id
  cross join counted
  order by f.created_at desc
  limit greatest(p_page_size, 1)
  offset greatest(p_page - 1, 0) * greatest(p_page_size, 1);
$$;

comment on function public.list_stores is
  'Server-side searched/filtered/paginated store list for the SaaS Store
   Management UI. total_count is repeated on every row so the caller can
   compute total pages without a second query.';

-- -----------------------------------------------------------------------------
-- saas_dashboard_summary
-- Aggregate counts for the SaaS dashboard cards. One query, no N+1.
-- -----------------------------------------------------------------------------
create or replace function public.saas_dashboard_summary()
returns table (
  total_stores bigint,
  active_stores bigint,
  suspended_stores bigint,
  archived_stores bigint,
  inactive_stores bigint,
  total_store_users bigint,
  stores_created_this_month bigint
)
language sql
stable
as $$
  select
    (select count(*) from public.stores) as total_stores,
    (select count(*) from public.stores where status = 'active') as active_stores,
    (select count(*) from public.stores where status = 'suspended') as suspended_stores,
    (select count(*) from public.stores where status = 'archived') as archived_stores,
    (select count(*) from public.stores where status = 'inactive') as inactive_stores,
    (select count(*) from public.store_users) as total_store_users,
    (select count(*) from public.stores where date_trunc('month', created_at) = date_trunc('month', now())) as stores_created_this_month;
$$;

comment on function public.saas_dashboard_summary is
  'Single-query aggregate counts backing the SaaS dashboard cards.';


-- #############################################################################
-- FILE: supabase/migrations/0016_subscription_plans.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0016_subscription_plans.sql
-- Purpose  : Phase 4 — SaaS Subscription Plans. Plans are platform-level
--            reference data managed by SaaS Admins; stores are linked to a
--            plan via store_subscriptions (0017), not by copying plan data
--            onto stores.
-- =============================================================================

create table if not exists public.subscription_plans (
  id                  uuid primary key default gen_random_uuid(),

  name                text not null,
  code                text not null,          -- e.g. 'TRIAL', 'STARTER', 'STANDARD', 'PRO', 'ENTERPRISE'
  description         text,

  monthly_price       numeric(12,2) not null default 0,
  yearly_price        numeric(12,2) not null default 0,
  currency_code       text not null default 'QAR',

  trial_days          integer not null default 0,

  max_users           integer,                -- null = unlimited
  max_branches        integer,
  max_products        integer,
  max_storage_mb      integer,

  status              text not null default 'active'
                       check (status in ('active', 'inactive', 'archived')),
  sort_order          integer not null default 0,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint subscription_plans_code_key unique (code),
  constraint subscription_plans_currency_len check (char_length(currency_code) = 3)
);

comment on table public.subscription_plans is
  'Platform-level subscription plan catalogue (Trial, Starter, Standard, Pro,
   Enterprise, ...). Managed by SaaS Admins. Stores link to a plan via
   store_subscriptions, never by copying plan fields onto stores.';

create index if not exists idx_subscription_plans_code on public.subscription_plans (code);
create index if not exists idx_subscription_plans_status on public.subscription_plans (status);

create trigger trg_subscription_plans_updated_at
  before update on public.subscription_plans
  for each row
  execute function public.set_updated_at();

alter table public.subscription_plans enable row level security;

-- -----------------------------------------------------------------------------
-- plan_features
-- Feature/module flags per plan, keyed by a stable string (e.g.
-- 'module.products', 'feature.loyalty') rather than hard-coding rules into
-- the frontend. limit_value is an optional numeric cap specific to that
-- feature (distinct from the plan-wide max_* columns above, which cover the
-- limits every plan needs regardless of feature toggles).
-- -----------------------------------------------------------------------------
create table if not exists public.plan_features (
  id                  uuid primary key default gen_random_uuid(),

  plan_id             uuid not null references public.subscription_plans (id) on delete cascade,
  feature_key         text not null,          -- e.g. 'module.products', 'feature.loyalty'
  enabled             boolean not null default true,
  limit_value         integer,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint plan_features_plan_key_key unique (plan_id, feature_key)
);

comment on table public.plan_features is
  'Per-plan feature/module toggles, keyed by a stable feature_key
   (module.products, feature.loyalty, ...). Future modules check this via
   has_store_feature()/requireStoreFeature() rather than hard-coded rules.';

create index if not exists idx_plan_features_plan_id on public.plan_features (plan_id);

create trigger trg_plan_features_updated_at
  before update on public.plan_features
  for each row
  execute function public.set_updated_at();

alter table public.plan_features enable row level security;

-- -----------------------------------------------------------------------------
-- Seed the platform's default plan catalogue as reference data (NOT
-- dev-only — every environment needs a Trial plan to exist for store
-- creation to auto-assign one). Idempotent via ON CONFLICT.
-- -----------------------------------------------------------------------------
insert into public.subscription_plans (name, code, description, monthly_price, yearly_price, currency_code, trial_days, max_users, max_branches, max_products, max_storage_mb, status, sort_order)
values
  ('Trial', 'TRIAL', 'Free trial with basic limits.', 0, 0, 'QAR', 14, 2, 1, 500, 1024, 'active', 0),
  ('Starter', 'STARTER', 'For small single-location stores.', 149, 1490, 'QAR', 0, 3, 1, 2000, 5120, 'active', 1),
  ('Standard', 'STANDARD', 'For growing stores with more staff.', 349, 3490, 'QAR', 0, 8, 2, 10000, 20480, 'active', 2),
  ('Professional', 'PRO', 'For multi-branch operations.', 699, 6990, 'QAR', 0, 20, 5, 50000, 51200, 'active', 3),
  ('Enterprise', 'ENTERPRISE', 'Custom limits for large operations.', 0, 0, 'QAR', 0, null, null, null, null, 'active', 4)
on conflict (code) do nothing;

-- Default feature set per plan. Trial/Starter get core modules only;
-- higher tiers unlock more. Future modules (loyalty, advanced reports,
-- multi-branch, exports) are already represented as keys even though the
-- modules themselves aren't built yet — Phase 5+ can wire them in without a
-- schema change.
insert into public.plan_features (plan_id, feature_key, enabled, limit_value)
select p.id, f.feature_key, f.enabled, f.limit_value
from public.subscription_plans p
cross join lateral (
  values
    ('module.products', true, null::integer),
    ('module.inventory', true, null::integer),
    ('module.pos', true, null::integer),
    ('module.purchases', p.code in ('STANDARD', 'PRO', 'ENTERPRISE'), null::integer),
    ('module.accounting', p.code in ('STANDARD', 'PRO', 'ENTERPRISE'), null::integer),
    ('feature.advanced_reports', p.code in ('PRO', 'ENTERPRISE'), null::integer),
    ('feature.loyalty', p.code in ('PRO', 'ENTERPRISE'), null::integer),
    ('feature.offers', p.code in ('STANDARD', 'PRO', 'ENTERPRISE'), null::integer),
    ('feature.multi_branch', p.code in ('PRO', 'ENTERPRISE'), null::integer),
    ('feature.exports', p.code <> 'TRIAL', null::integer),
    ('feature.barcode', true, null::integer)
) as f(feature_key, enabled, limit_value)
on conflict (plan_id, feature_key) do nothing;


-- #############################################################################
-- FILE: supabase/migrations/0017_store_subscriptions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0017_store_subscriptions.sql
-- Purpose  : Links stores to a subscription plan, and keeps an append-only
--            history of every change.
--
-- DESIGN DECISION — "one current subscription per store":
-- store_subscriptions has a UNIQUE constraint on store_id, so there is
-- exactly ONE row per store, ever. Renewals, plan changes, extensions, and
-- status changes UPDATE that row in place (current_period_start/end,
-- plan_id, status, etc.) rather than inserting a new "subscription" each
-- time. This trivially guarantees "a store cannot have multiple conflicting
-- active subscriptions" — there is structurally only one row to conflict
-- with. Full history of every change (old plan, new plan, old status, new
-- status, who did it, when) is preserved separately in
-- subscription_history, which IS append-only and grows over time. This
-- avoids the two-source-of-truth problem the spec warns about: the current
-- state lives in exactly one place (store_subscriptions), and everything
-- that ever happened lives in exactly one other place (subscription_history).
-- =============================================================================

create table if not exists public.store_subscriptions (
  id                    uuid primary key default gen_random_uuid(),

  store_id              uuid not null references public.stores (id) on delete cascade,
  plan_id               uuid not null references public.subscription_plans (id),

  status                text not null default 'trial'
                         check (status in ('trial', 'active', 'expired', 'suspended', 'cancelled')),
  billing_cycle         text not null default 'trial'
                         check (billing_cycle in ('trial', 'monthly', 'yearly', 'custom')),

  started_at            timestamptz not null default now(),
  trial_ends_at         timestamptz,

  current_period_start  timestamptz not null default now(),
  current_period_end    timestamptz not null,

  -- Optional grace period foundation (Phase 4 §35). Not exposed in any UI
  -- yet — schema-ready for a future phase to turn on without a migration.
  grace_period_days     integer not null default 0,

  expires_at            timestamptz,
  cancelled_at          timestamptz,
  notes                 text,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid references public.saas_admins (id) on delete set null,

  constraint store_subscriptions_store_id_key unique (store_id)
);

comment on table public.store_subscriptions is
  'Exactly one row per store (unique store_id) — the CURRENT subscription
   state. Every change is applied in place here and separately logged to
   subscription_history. See migration header for the full rationale.';

create index if not exists idx_store_subscriptions_store_id on public.store_subscriptions (store_id);
create index if not exists idx_store_subscriptions_plan_id on public.store_subscriptions (plan_id);
create index if not exists idx_store_subscriptions_status on public.store_subscriptions (status);
create index if not exists idx_store_subscriptions_period_end on public.store_subscriptions (current_period_end);

create trigger trg_store_subscriptions_updated_at
  before update on public.store_subscriptions
  for each row
  execute function public.set_updated_at();

alter table public.store_subscriptions enable row level security;

-- -----------------------------------------------------------------------------
-- subscription_history — append-only, never updated or deleted.
-- -----------------------------------------------------------------------------
create table if not exists public.subscription_history (
  id                      uuid primary key default gen_random_uuid(),

  store_id                uuid not null references public.stores (id) on delete cascade,
  subscription_id         uuid references public.store_subscriptions (id) on delete set null,

  old_plan_id             uuid references public.subscription_plans (id),
  new_plan_id             uuid references public.subscription_plans (id),
  old_status              text,
  new_status              text not null,

  -- e.g. 'trial_started', 'plan_assigned', 'upgraded', 'downgraded',
  -- 'renewed', 'extended', 'suspended', 'expired', 'cancelled'
  action                  text not null,

  effective_at            timestamptz not null default now(),
  performed_by_saas_admin uuid references public.saas_admins (id) on delete set null,
  metadata                jsonb,

  created_at              timestamptz not null default now()
);

comment on table public.subscription_history is
  'Append-only audit trail of every subscription change. Never updated or
   deleted — this is the historical record store_subscriptions itself does
   not keep (that table only holds current state).';

create index if not exists idx_subscription_history_store_created on public.subscription_history (store_id, created_at);
create index if not exists idx_subscription_history_subscription_id on public.subscription_history (subscription_id);

alter table public.subscription_history enable row level security;


-- #############################################################################
-- FILE: supabase/migrations/0018_subscription_functions.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0018_subscription_functions.sql
-- Purpose  : Atomic subscription management operations, plan-limit and
--            feature-access helpers, and extending create_store_with_admin
--            to auto-assign a subscription (Trial by default) atomically
--            with store creation.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- assign_store_subscription
-- Creates or replaces a store's ONE subscription row (see 0017 header for
-- why this is an upsert, not an insert-only history). Used directly for
-- initial assignment, and as the building block other functions below call.
-- -----------------------------------------------------------------------------
create or replace function public.assign_store_subscription(
  p_store_id uuid,
  p_plan_id uuid,
  p_billing_cycle text,
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_status text,
  p_saas_admin_id uuid,
  p_action text,
  p_notes text default null,
  p_trial_ends_at timestamptz default null
)
returns uuid
language plpgsql
as $$
declare
  v_subscription_id uuid;
  v_old_plan_id uuid;
  v_old_status text;
begin
  select id, plan_id, status into v_subscription_id, v_old_plan_id, v_old_status
  from public.store_subscriptions where store_id = p_store_id;

  if v_subscription_id is null then
    insert into public.store_subscriptions (
      store_id, plan_id, status, billing_cycle, started_at, trial_ends_at,
      current_period_start, current_period_end, notes, created_by
    ) values (
      p_store_id, p_plan_id, p_status, p_billing_cycle, now(), p_trial_ends_at,
      p_period_start, p_period_end, p_notes, p_saas_admin_id
    )
    returning id into v_subscription_id;
  else
    update public.store_subscriptions set
      plan_id = p_plan_id,
      status = p_status,
      billing_cycle = p_billing_cycle,
      trial_ends_at = coalesce(p_trial_ends_at, trial_ends_at),
      current_period_start = p_period_start,
      current_period_end = p_period_end,
      notes = coalesce(p_notes, notes),
      cancelled_at = case when p_status = 'cancelled' then now() else null end
    where id = v_subscription_id;
  end if;

  insert into public.subscription_history (
    store_id, subscription_id, old_plan_id, new_plan_id, old_status, new_status,
    action, performed_by_saas_admin, metadata
  ) values (
    p_store_id, v_subscription_id, v_old_plan_id, p_plan_id, v_old_status, p_status,
    p_action, p_saas_admin_id, jsonb_build_object('periodStart', p_period_start, 'periodEnd', p_period_end)
  );

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, new_values)
  values (p_store_id, p_saas_admin_id, 'saas_subscription_management', p_action, 'store_subscription', v_subscription_id,
    jsonb_build_object('planId', p_plan_id, 'status', p_status));

  return v_subscription_id;
end;
$$;

comment on function public.assign_store_subscription is
  'Creates or updates the store''s single current subscription row, logs the
   change to subscription_history, and writes an audit entry. Atomic.';

-- -----------------------------------------------------------------------------
-- renew_store_subscription
-- -----------------------------------------------------------------------------
create or replace function public.renew_store_subscription(
  p_store_id uuid,
  p_period_end timestamptz,
  p_billing_cycle text,
  p_saas_admin_id uuid,
  p_notes text default null
)
returns uuid
language plpgsql
as $$
declare
  v_current_end timestamptz;
  v_plan_id uuid;
  v_period_start timestamptz;
begin
  select current_period_end, plan_id into v_current_end, v_plan_id
  from public.store_subscriptions where store_id = p_store_id;

  if v_plan_id is null then
    raise exception 'store has no subscription to renew: %', p_store_id;
  end if;

  v_period_start := greatest(coalesce(v_current_end, now()), now());

  return public.assign_store_subscription(
    p_store_id, v_plan_id, p_billing_cycle, v_period_start, p_period_end, 'active',
    p_saas_admin_id, 'subscription_renewed', p_notes
  );
end;
$$;

comment on function public.renew_store_subscription is
  'Renews a store''s current plan for a new period. If the previous period
   has not yet ended, the new period starts from the old end date rather
   than "now" so paid time is never lost.';

-- -----------------------------------------------------------------------------
-- extend_store_subscription
-- -----------------------------------------------------------------------------
create or replace function public.extend_store_subscription(
  p_store_id uuid,
  p_new_period_end timestamptz,
  p_saas_admin_id uuid,
  p_reason text default null
)
returns uuid
language plpgsql
as $$
declare
  v_subscription_id uuid;
  v_plan_id uuid;
  v_status text;
  v_old_period_end timestamptz;
begin
  select id, plan_id, status, current_period_end
  into v_subscription_id, v_plan_id, v_status, v_old_period_end
  from public.store_subscriptions where store_id = p_store_id;

  if v_subscription_id is null then
    raise exception 'store has no subscription to extend: %', p_store_id;
  end if;

  update public.store_subscriptions
  set current_period_end = p_new_period_end,
      status = case when status = 'expired' then 'active' else status end
  where id = v_subscription_id;

  insert into public.subscription_history (
    store_id, subscription_id, old_plan_id, new_plan_id, old_status, new_status, action, performed_by_saas_admin, metadata
  ) values (
    p_store_id, v_subscription_id, v_plan_id, v_plan_id, v_status,
    case when v_status = 'expired' then 'active' else v_status end,
    'subscription_extended', p_saas_admin_id,
    jsonb_build_object('previousPeriodEnd', v_old_period_end, 'newPeriodEnd', p_new_period_end, 'reason', p_reason)
  );

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, old_values, new_values)
  values (p_store_id, p_saas_admin_id, 'saas_subscription_management', 'subscription_extended', 'store_subscription', v_subscription_id,
    jsonb_build_object('periodEnd', v_old_period_end), jsonb_build_object('periodEnd', p_new_period_end));

  return v_subscription_id;
end;
$$;

comment on function public.extend_store_subscription is
  'Pushes a store''s current_period_end forward (or to a custom date)
   without changing its plan. Reactivates an expired subscription. Records
   previous/new expiry, the acting admin, and an optional reason.';

-- -----------------------------------------------------------------------------
-- change_store_subscription_plan
-- -----------------------------------------------------------------------------
create or replace function public.change_store_subscription_plan(
  p_store_id uuid,
  p_new_plan_id uuid,
  p_billing_cycle text,
  p_period_end timestamptz,
  p_saas_admin_id uuid,
  p_notes text default null
)
returns uuid
language plpgsql
as $$
begin
  return public.assign_store_subscription(
    p_store_id, p_new_plan_id, p_billing_cycle, now(), p_period_end, 'active',
    p_saas_admin_id, 'subscription_changed', p_notes
  );
end;
$$;

comment on function public.change_store_subscription_plan is
  'Changes a store''s plan (upgrade or downgrade), starting a new period
   immediately. Phase 4 applies plan changes immediately per spec §29.';

-- -----------------------------------------------------------------------------
-- set_subscription_status (distinct from set_store_status — see Phase 4 §33)
-- -----------------------------------------------------------------------------
create or replace function public.set_subscription_status(
  p_store_id uuid,
  p_new_status text,
  p_saas_admin_id uuid,
  p_notes text default null
)
returns uuid
language plpgsql
as $$
declare
  v_subscription_id uuid;
  v_plan_id uuid;
  v_old_status text;
begin
  if p_new_status not in ('trial', 'active', 'expired', 'suspended', 'cancelled') then
    raise exception 'invalid subscription status: %', p_new_status;
  end if;

  select id, plan_id, status into v_subscription_id, v_plan_id, v_old_status
  from public.store_subscriptions where store_id = p_store_id;

  if v_subscription_id is null then
    raise exception 'store has no subscription: %', p_store_id;
  end if;

  update public.store_subscriptions
  set status = p_new_status,
      cancelled_at = case when p_new_status = 'cancelled' then now() else cancelled_at end,
      notes = coalesce(p_notes, notes)
  where id = v_subscription_id;

  insert into public.subscription_history (
    store_id, subscription_id, old_plan_id, new_plan_id, old_status, new_status, action, performed_by_saas_admin, metadata
  ) values (
    p_store_id, v_subscription_id, v_plan_id, v_plan_id, v_old_status, p_new_status,
    'subscription_' || p_new_status, p_saas_admin_id, jsonb_build_object('notes', p_notes)
  );

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, old_values, new_values)
  values (p_store_id, p_saas_admin_id, 'saas_subscription_management', 'subscription_' || p_new_status, 'store_subscription', v_subscription_id,
    jsonb_build_object('status', v_old_status), jsonb_build_object('status', p_new_status));

  return v_subscription_id;
end;
$$;

comment on function public.set_subscription_status is
  'Suspends/cancels/reactivates a SUBSCRIPTION (not the store itself — a
   store can stay active while its subscription is suspended/expired).';

-- -----------------------------------------------------------------------------
-- get_store_subscription_context
-- -----------------------------------------------------------------------------
create or replace function public.get_store_subscription_context(p_store_id uuid)
returns table (
  subscription_id uuid,
  plan_id uuid,
  plan_name text,
  plan_code text,
  status text,
  effective_status text,
  billing_cycle text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  days_remaining integer,
  max_users integer,
  max_branches integer,
  max_products integer,
  max_storage_mb integer,
  feature_keys text[]
)
language sql
stable
as $$
  select
    ss.id, sp.id, sp.name, sp.code, ss.status,
    case
      when ss.status in ('suspended', 'cancelled') then ss.status
      when ss.current_period_end < now() then 'expired'
      else ss.status
    end as effective_status,
    ss.billing_cycle, ss.current_period_start, ss.current_period_end,
    greatest(0, ceil(extract(epoch from (ss.current_period_end - now())) / 86400))::integer as days_remaining,
    sp.max_users, sp.max_branches, sp.max_products, sp.max_storage_mb,
    coalesce(
      (select array_agg(pf.feature_key) from public.plan_features pf where pf.plan_id = sp.id and pf.enabled),
      array[]::text[]
    ) as feature_keys
  from public.store_subscriptions ss
  join public.subscription_plans sp on sp.id = ss.plan_id
  where ss.store_id = p_store_id;
$$;

comment on function public.get_store_subscription_context is
  'Everything the session layer / store details page needs about a store''s
   subscription in one query. effective_status computes expiry on read
   (current_period_end < now()) so a stale stored status can never grant
   access past the paid period, even before any scheduled job updates it.';

-- -----------------------------------------------------------------------------
-- check_plan_limit
-- -----------------------------------------------------------------------------
create or replace function public.check_plan_limit(p_store_id uuid, p_limit_key text)
returns table (current_count integer, limit_value integer, allowed boolean)
language plpgsql
stable
as $$
declare
  v_current integer;
  v_limit integer;
begin
  select
    case p_limit_key
      when 'users' then (select count(*)::integer from public.store_users where store_id = p_store_id)
      else null
    end,
    case p_limit_key
      when 'users' then (select sp.max_users from public.store_subscriptions ss join public.subscription_plans sp on sp.id = ss.plan_id where ss.store_id = p_store_id)
      when 'branches' then (select sp.max_branches from public.store_subscriptions ss join public.subscription_plans sp on sp.id = ss.plan_id where ss.store_id = p_store_id)
      when 'products' then (select sp.max_products from public.store_subscriptions ss join public.subscription_plans sp on sp.id = ss.plan_id where ss.store_id = p_store_id)
      else null
    end
  into v_current, v_limit;

  return query select v_current, v_limit, (v_limit is null or v_current < v_limit);
end;
$$;

comment on function public.check_plan_limit is
  'Generic plan-limit check. limit_value NULL means unlimited (allowed is
   always true). "users" is wired against real data now; "branches"/
   "products" return the plan limit with current_count NULL until those
   modules exist (Phase 5+ fills in the counting logic).';

-- -----------------------------------------------------------------------------
-- has_store_feature
-- -----------------------------------------------------------------------------
create or replace function public.has_store_feature(p_store_id uuid, p_feature_key text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.store_subscriptions ss
    join public.plan_features pf on pf.plan_id = ss.plan_id
    where ss.store_id = p_store_id
      and pf.feature_key = p_feature_key
      and pf.enabled = true
  );
$$;

comment on function public.has_store_feature is
  'True if the store''s current plan has the given feature_key enabled.
   Used by future modules'' requireStoreFeature() backend guard.';

-- -----------------------------------------------------------------------------
-- Extend create_store_with_admin (Phase 3) with trailing optional params so
-- existing callers keep working unchanged. If p_plan_id is omitted, the
-- TRIAL plan is looked up by code and assigned with its configured
-- trial_days — "Recommended default: Trial plan".
-- -----------------------------------------------------------------------------
create or replace function public.create_store_with_admin(
  p_business_name text,
  p_legal_name text,
  p_owner_name text,
  p_mobile text,
  p_whatsapp text,
  p_email text,
  p_address_line_1 text,
  p_address_line_2 text,
  p_city text,
  p_state text,
  p_country text,
  p_postal_code text,
  p_currency_code text,
  p_timezone text,
  p_tax_number text,
  p_created_by uuid,
  p_admin_full_name text,
  p_admin_login_id text,
  p_admin_password_hash text,
  p_admin_phone text,
  p_plan_id uuid default null,
  p_billing_cycle text default null
)
returns table (
  store_id uuid,
  store_code text,
  admin_user_id uuid,
  role_id uuid,
  subscription_id uuid
)
language plpgsql
as $$
declare
  v_store_id uuid;
  v_store_code text;
  v_role_id uuid;
  v_admin_user_id uuid;
  v_permission_ids uuid[];
  v_plan_id uuid;
  v_trial_days integer;
  v_billing_cycle text;
  v_subscription_id uuid;
begin
  insert into public.stores (
    business_name, legal_name, owner_name, mobile, whatsapp, email,
    address_line_1, address_line_2, city, state, country, postal_code,
    currency_code, timezone, tax_number, status, created_by
  ) values (
    p_business_name, nullif(p_legal_name, ''), p_owner_name, p_mobile, nullif(p_whatsapp, ''), nullif(p_email, ''),
    p_address_line_1, nullif(p_address_line_2, ''), nullif(p_city, ''), nullif(p_state, ''), p_country, nullif(p_postal_code, ''),
    p_currency_code, p_timezone, nullif(p_tax_number, ''), 'active', p_created_by
  )
  returning id, stores.store_code into v_store_id, v_store_code;

  select id into v_role_id from public.roles where store_id = v_store_id and name = 'Store Admin';
  if v_role_id is null then
    insert into public.roles (store_id, name, description, is_system_role, status)
    values (v_store_id, 'Store Admin', 'Full access within this store', false, 'active')
    returning id into v_role_id;
  end if;

  select array_agg(id) into v_permission_ids from public.permissions;
  if v_permission_ids is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_role_id, unnest(v_permission_ids)
    on conflict (role_id, permission_id) do nothing;
  end if;

  insert into public.store_users (store_id, login_id, password_hash, full_name, phone, role_id, status, created_by)
  values (v_store_id, p_admin_login_id, p_admin_password_hash, p_admin_full_name, nullif(p_admin_phone, ''), v_role_id, 'active', null)
  returning id into v_admin_user_id;

  insert into public.store_settings (store_id, setting_key, setting_value)
  values (v_store_id, 'general', '{}'::jsonb)
  on conflict (store_id, setting_key) do nothing;

  -- --- Phase 4: subscription assignment ---
  v_plan_id := p_plan_id;
  if v_plan_id is null then
    select id, trial_days into v_plan_id, v_trial_days from public.subscription_plans where code = 'TRIAL';
  else
    select trial_days into v_trial_days from public.subscription_plans where id = v_plan_id;
  end if;

  if v_plan_id is not null then
    v_billing_cycle := coalesce(p_billing_cycle, case when p_plan_id is null then 'trial' else 'monthly' end);

    insert into public.store_subscriptions (
      store_id, plan_id, status, billing_cycle, started_at, trial_ends_at, current_period_start, current_period_end, created_by
    ) values (
      v_store_id, v_plan_id,
      case when v_billing_cycle = 'trial' then 'trial' else 'active' end,
      v_billing_cycle, now(),
      case when v_billing_cycle = 'trial' then now() + make_interval(days => coalesce(v_trial_days, 14)) else null end,
      now(),
      case when v_billing_cycle = 'trial' then now() + make_interval(days => coalesce(v_trial_days, 14))
           when v_billing_cycle = 'yearly' then now() + interval '1 year'
           else now() + interval '1 month' end,
      p_created_by
    )
    returning id into v_subscription_id;

    insert into public.subscription_history (store_id, subscription_id, new_plan_id, new_status, action, performed_by_saas_admin)
    values (v_store_id, v_subscription_id, v_plan_id, case when v_billing_cycle = 'trial' then 'trial' else 'active' end, 'trial_started', p_created_by);
  end if;

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, new_values)
  values (v_store_id, p_created_by, 'saas_store_management', 'store_created', 'store', v_store_id,
    jsonb_build_object('storeCode', v_store_code, 'businessName', p_business_name, 'planId', v_plan_id));

  return query select v_store_id, v_store_code, v_admin_user_id, v_role_id, v_subscription_id;
end;
$$;

comment on function public.create_store_with_admin is
  'Atomically creates a store, its Store Admin role + permissions, the
   initial Store Admin user, default settings, AND a subscription (the
   given plan, or TRIAL by default) with its history entry, plus the store
   audit entry. One transaction — any exception rolls back everything,
   including the subscription.';


-- #############################################################################
-- FILE: supabase/migrations/0019_subscription_list_and_dashboard.sql
-- #############################################################################

-- =============================================================================
-- Migration: 0019_subscription_list_and_dashboard.sql
-- Purpose  : Server-side list/search functions for the Plans and
--            Subscriptions pages, plus extended SaaS dashboard metrics
--            covering trial/expiring/expired subscription counts.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- list_plans_with_store_counts
-- -----------------------------------------------------------------------------
create or replace function public.list_plans_with_store_counts()
returns table (
  id uuid,
  name text,
  code text,
  description text,
  monthly_price numeric,
  yearly_price numeric,
  currency_code text,
  trial_days integer,
  max_users integer,
  max_branches integer,
  max_products integer,
  max_storage_mb integer,
  status text,
  sort_order integer,
  store_count bigint
)
language sql
stable
as $$
  select
    p.id, p.name, p.code, p.description, p.monthly_price, p.yearly_price, p.currency_code,
    p.trial_days, p.max_users, p.max_branches, p.max_products, p.max_storage_mb, p.status, p.sort_order,
    coalesce(s.store_count, 0) as store_count
  from public.subscription_plans p
  left join (
    select plan_id, count(*) as store_count from public.store_subscriptions group by plan_id
  ) s on s.plan_id = p.id
  order by p.sort_order, p.name;
$$;

comment on function public.list_plans_with_store_counts is
  'All plans with how many stores currently use each -- backs the /saas/plans list and the "used by N stores" edit warning.';

-- -----------------------------------------------------------------------------
-- list_store_subscriptions
-- -----------------------------------------------------------------------------
create or replace function public.list_store_subscriptions(
  p_search text default null,
  p_plan_id uuid default null,
  p_status text default null,
  p_billing_cycle text default null,
  p_expiring_within_days integer default null,
  p_page integer default 1,
  p_page_size integer default 20
)
returns table (
  store_id uuid,
  store_code text,
  business_name text,
  plan_id uuid,
  plan_name text,
  status text,
  effective_status text,
  billing_cycle text,
  started_at timestamptz,
  current_period_end timestamptz,
  days_remaining integer,
  total_count bigint
)
language sql
stable
as $$
  with base as (
    select
      s.id as store_id, s.store_code, s.business_name,
      sp.id as plan_id, sp.name as plan_name,
      ss.status, ss.billing_cycle, ss.started_at, ss.current_period_end,
      case
        when ss.status in ('suspended', 'cancelled') then ss.status
        when ss.current_period_end < now() then 'expired'
        else ss.status
      end as effective_status,
      greatest(0, ceil(extract(epoch from (ss.current_period_end - now())) / 86400))::integer as days_remaining
    from public.store_subscriptions ss
    join public.stores s on s.id = ss.store_id
    join public.subscription_plans sp on sp.id = ss.plan_id
  ),
  filtered as (
    select * from base
    where (p_plan_id is null or plan_id = p_plan_id)
      and (p_status is null or effective_status = p_status)
      and (p_billing_cycle is null or billing_cycle = p_billing_cycle)
      and (p_expiring_within_days is null or (days_remaining <= p_expiring_within_days and effective_status in ('trial', 'active')))
      and (
        p_search is null or p_search = '' or
        store_code ilike '%' || p_search || '%' or
        business_name ilike '%' || p_search || '%'
      )
  ),
  counted as (select count(*) as total from filtered)
  select f.*, counted.total
  from filtered f
  cross join counted
  order by f.current_period_end asc
  limit greatest(p_page_size, 1)
  offset greatest(p_page - 1, 0) * greatest(p_page_size, 1);
$$;

comment on function public.list_store_subscriptions is
  'Server-side searched/filtered/paginated subscription list for
   /saas/subscriptions, including an "expiring within N days" filter.';

-- -----------------------------------------------------------------------------
-- saas_subscription_dashboard_summary
-- -----------------------------------------------------------------------------
create or replace function public.saas_subscription_dashboard_summary()
returns table (
  trial_stores bigint,
  active_subscriptions bigint,
  expired_subscriptions bigint,
  expiring_within_7_days bigint,
  expiring_within_30_days bigint
)
language sql
stable
as $$
  with computed as (
    select
      case
        when status in ('suspended', 'cancelled') then status
        when current_period_end < now() then 'expired'
        else status
      end as effective_status,
      current_period_end
    from public.store_subscriptions
  )
  select
    (select count(*) from computed where effective_status = 'trial') as trial_stores,
    (select count(*) from computed where effective_status = 'active') as active_subscriptions,
    (select count(*) from computed where effective_status = 'expired') as expired_subscriptions,
    (select count(*) from computed where effective_status in ('trial','active') and current_period_end < now() + interval '7 days') as expiring_within_7_days,
    (select count(*) from computed where effective_status in ('trial','active') and current_period_end < now() + interval '30 days') as expiring_within_30_days;
$$;

comment on function public.saas_subscription_dashboard_summary is
  'Subscription-specific counts (trial/active/expired/expiring soon) for the SaaS dashboard.';

