-- =============================================================================
-- Migration: 0014_store_management_functions.sql
-- Purpose  : Phase 3 — SaaS Super Admin Store Management. Atomic store
--            creation (store + role + permissions + admin user + settings +
--            audit, all-or-nothing), plus safe status-change and session
--            revocation helpers used by the store management Edge Functions.
-- =============================================================================

-- pg_trgm powers the fuzzy/substring search indexes used below for the
-- store search endpoint (business name / owner name).
create extension if not exists "pg_trgm";

-- -----------------------------------------------------------------------------
-- create_store_with_admin
--
-- Runs the entire "create a tenant" flow as ONE Postgres function call, which
-- Postgres executes inside an implicit transaction — if any step raises, the
-- whole thing rolls back automatically (no store without an admin, no admin
-- without a role, no partially-initialized store). This is the safe
-- transactional implementation requested in Phase 3 §12/§48.
--
-- Password hashing does NOT happen in Postgres — p_password_hash is already
-- a bcrypt hash computed in the Edge Function (see
-- supabase/functions/_shared/password.ts) before calling this. Postgres has
-- no vetted, maintained bcrypt/argon2 implementation available by default
-- (no pgcrypto crypt() blowfish support is enabled here), and re-implementing
-- password hashing in SQL would create a second hashing code path to keep in
-- sync with the Edge Function one — a needless risk. Hashing stays in
-- trusted server-side JS/TS; this function just persists the result.
-- -----------------------------------------------------------------------------
create or replace function public.create_store_with_admin(
  p_business_name text,
  p_legal_name text,
  p_owner_name text,
  p_mobile text,
  p_whatsapp text,
  p_email text,
  p_address_line_1 text,
  p_address_line_2 text,
  p_city text,
  p_state text,
  p_country text,
  p_postal_code text,
  p_currency_code text,
  p_timezone text,
  p_tax_number text,
  p_created_by uuid,          -- saas_admins.id of the creator
  p_admin_full_name text,
  p_admin_login_id text,
  p_admin_password_hash text,
  p_admin_phone text
)
returns table (
  store_id uuid,
  store_code text,
  admin_user_id uuid,
  role_id uuid
)
language plpgsql
as $$
declare
  v_store_id uuid;
  v_store_code text;
  v_role_id uuid;
  v_admin_user_id uuid;
  v_permission_ids uuid[];
begin
  -- 1. Insert store (store_code generated by generate_store_code() default).
  insert into public.stores (
    business_name, legal_name, owner_name, mobile, whatsapp, email,
    address_line_1, address_line_2, city, state, country, postal_code,
    currency_code, timezone, tax_number, status, created_by
  ) values (
    p_business_name, nullif(p_legal_name, ''), p_owner_name, p_mobile, nullif(p_whatsapp, ''), nullif(p_email, ''),
    p_address_line_1, nullif(p_address_line_2, ''), nullif(p_city, ''), nullif(p_state, ''), p_country, nullif(p_postal_code, ''),
    p_currency_code, p_timezone, nullif(p_tax_number, ''), 'active', p_created_by
  )
  returning id, stores.store_code into v_store_id, v_store_code;

  -- 2. Create the store's "Store Admin" role if it doesn't already exist
  --    (defensive — a fresh store never has one yet, but this keeps the
  --    function idempotent-safe rather than erroring on a retry).
  select id into v_role_id
  from public.roles
  where store_id = v_store_id and name = 'Store Admin';

  if v_role_id is null then
    insert into public.roles (store_id, name, description, is_system_role, status)
    values (v_store_id, 'Store Admin', 'Full access within this store', false, 'active')
    returning id into v_role_id;
  end if;

  -- 3. Assign the foundation permissions available at this stage to the new
  --    role (all currently-seeded permissions — Phase 5 expands this set).
  select array_agg(id) into v_permission_ids from public.permissions;

  if v_permission_ids is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_role_id, unnest(v_permission_ids)
    on conflict (role_id, permission_id) do nothing;
  end if;

  -- 4. Create the initial Store Admin user (password already hashed by caller).
  insert into public.store_users (
    store_id, login_id, password_hash, full_name, phone, role_id, status, created_by
  ) values (
    v_store_id, p_admin_login_id, p_admin_password_hash, p_admin_full_name, nullif(p_admin_phone, ''), v_role_id, 'active', null
  )
  returning id into v_admin_user_id;

  -- 5. Default store settings row(s) — empty JSONB placeholders future
  --    phases will populate (invoice config, receipt config, etc).
  insert into public.store_settings (store_id, setting_key, setting_value)
  values (v_store_id, 'general', '{}'::jsonb)
  on conflict (store_id, setting_key) do nothing;

  -- 6. Audit entry (the Edge Function also writes its own higher-level
  --    audit row with the acting SaaS admin's IP; this one captures the
  --    atomic DB-side fact that the transaction completed).
  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, new_values)
  values (
    v_store_id, p_created_by, 'saas_store_management', 'store_created', 'store', v_store_id,
    jsonb_build_object('storeCode', v_store_code, 'businessName', p_business_name)
  );

  return query select v_store_id, v_store_code, v_admin_user_id, v_role_id;
end;
$$;

comment on function public.create_store_with_admin is
  'Atomically creates a store, its Store Admin role + permissions, the
   initial Store Admin user, default settings, and an audit entry. Runs in
   Postgres''s implicit function-call transaction: any exception rolls back
   the entire operation. Password must already be hashed by the caller.';

-- -----------------------------------------------------------------------------
-- set_store_status
--
-- Safe, audited status transition + session revocation in one call. Used by
-- the suspend/activate/archive Edge Function endpoints instead of a bare
-- `update stores set status = ...`, so revocation can never be forgotten.
-- -----------------------------------------------------------------------------
create or replace function public.set_store_status(
  p_store_id uuid,
  p_new_status text,
  p_saas_admin_id uuid
)
returns table (revoked_session_count integer)
language plpgsql
as $$
declare
  v_old_status text;
  v_revoked_count integer := 0;
begin
  if p_new_status not in ('active', 'suspended', 'inactive', 'archived') then
    raise exception 'invalid store status: %', p_new_status;
  end if;

  select status into v_old_status from public.stores where id = p_store_id for update;
  if v_old_status is null then
    raise exception 'store not found: %', p_store_id;
  end if;

  update public.stores set status = p_new_status where id = p_store_id;

  -- Revoke every active session for this store whenever it leaves 'active'
  -- status, so an old cookie can never keep working after suspend/archive.
  if p_new_status <> 'active' then
    with revoked as (
      update public.store_user_sessions
      set revoked_at = now()
      where store_id = p_store_id and revoked_at is null
      returning id
    )
    select count(*) into v_revoked_count from revoked;
  end if;

  insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, old_values, new_values)
  values (
    p_store_id, p_saas_admin_id, 'saas_store_management',
    case p_new_status
      when 'suspended' then 'store_suspended'
      when 'active' then 'store_activated'
      when 'archived' then 'store_archived'
      else 'store_updated'
    end,
    'store', p_store_id,
    jsonb_build_object('status', v_old_status),
    jsonb_build_object('status', p_new_status)
  );

  if v_revoked_count > 0 then
    insert into public.audit_logs (store_id, saas_admin_id, module, action, entity_type, entity_id, metadata)
    values (p_store_id, p_saas_admin_id, 'saas_store_management', 'store_sessions_revoked', 'store', p_store_id,
      jsonb_build_object('revokedCount', v_revoked_count));
  end if;

  return query select v_revoked_count;
end;
$$;

comment on function public.set_store_status is
  'Atomically updates a store''s status, revokes all its active store_user
   sessions if leaving "active" status, and writes audit log entries.';

-- -----------------------------------------------------------------------------
-- Indexes to support Phase 3 search/filter/pagination without full scans.
-- -----------------------------------------------------------------------------
create index if not exists idx_stores_country on public.stores (country);
create index if not exists idx_stores_created_at on public.stores (created_at desc);
-- Case-insensitive search across the fields the store list supports search on.
create index if not exists idx_stores_business_name_trgm on public.stores using gin (business_name gin_trgm_ops);
create index if not exists idx_stores_owner_name_trgm on public.stores using gin (owner_name gin_trgm_ops);
